# Generated by Django 4.2.13 on 2024-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("Starter", "Starter"),
                    ("main courses", "main courses"),
                    ("desserts", "desserts"),
                ],
                max_length=25,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
